name: ci

on: [push] 

jobs:
  build-image:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@main
    - name: Build Docker image
      run: |
        echo "start build"
        docker build --file ./docker/pytorch_1_4/Dockerfile --tag forecast-keiba:latest ./docker/pytorch_1_4/