name: ci

on: [push] 

jobs:
  build-image:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@main
    - name: Build Docker image
      run: |
        echo "start build"
        echo "$(pwd)"
        wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
        echo "$(ls)"
        docker build --file ./docker/pytorch_1_4/Dockerfile --tag forecast-keiba:latest ./docker/pytorch_1_4/
        cd ./docker/pytorch_1_4 && bash run_ci.sh docker && cd -
        echo "end build"