name: ci

on: [push] 

jobs:
  build-image:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@main
    - name: Build Docker image
      run: |
        echo "start build"
        echo "$(pwd)"
        sudo apt-get install -y wget
        wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
        cp google-chrome-stable_current_amd64.deb docker/pytorch_1_4/
        echo "$(ls)"
        cd docker/pytorch_1_4 && docker build --tag forecast-keiba:latest . && cd -
        cd docker/pytorch_1_4 && bash run_ci.sh docker && cd -
        echo "end build"